### ISSUE TITLE
Baichuan2-13B-Chat inference problem

### ISSUE THREAD

**Issue by fengenbao** [intel/intel-extension-for-transformers#1148] opened 2024-01-17 06:56 UTC
When I use Baichuan2-13B Chat for inference, I use the official method of building a prompt, BAICHUAN_ PROMPT_ FORM="<| human |>{prompt}<| bot |>" or messages=[{"role": "user", "content": prompt}], then use the official build_chat_input using the input function、, and then sent into the generate function, cannot obtain good output, for example, in the following example, how can I solve this problem?
![image](https://github.com/intel/intel-extension-for-transformers/assets/57557769/c6752660-fe77-4cd3-8cc9-577da5e2a807)

![image](https://github.com/intel/intel-extension-for-transformers/assets/57557769/9b285524-7efa-49de-82c2-e0089f9965f5)

**Comment by Zhenzhong1** [comment] 2024-01-22 09:48
@fengenbao Hi, I can't reproduce your error, because I don't know all your commands, prompts and installation methods.

But, it's ok. As you know, LLM runtime of the ITREX has been rebuilt to this repo: https://github.com/intel/neural-speed

I checked the baichuan output. Please check this PR https://github.com/intel/neural-speed/pull/80 and branch zhenzhong/APIissues.

Please 
`git clone https://github.com/intel/neural-speed`
`git checkout zhenzhong/APIissues`

Three commands and you will get results.
```python

pip install -r requirements.txt
python setup.py install
# home/model/Baichuan2-13B-Chat/  is a local baichuan path
python scripts/run.py /home/model/Baichuan2-13B-Chat/ --weight_dtype int4 -p "你好"

```
![image](https://github.com/intel/intel-extension-for-transformers/assets/109137058/6891b303-727f-441e-acca-8518f1d3143d)

The output looks good.

**Comment by Zhenzhong1** [comment] 2024-02-18 07:12
Hi. It's been a long time since I heard from you.

I closed this issue. If you have more questions, please feel free to ask.

**Closed by Zhenzhong1** 2024-02-18 07:12 UTC
