### ISSUE TITLE
Seg Fault error while inference , model : Intel/neural-chat-7b-v1-1

### ISSUE THREAD

**Issue by tsantra** [intel/intel-extension-for-transformers#411] opened 2023-10-03 22:11 UTC
Hi,
I am getting this Seg fault error. 

<img width="1028" alt="image" src="https://github.com/intel/intel-extension-for-transformers/assets/45886215/af0c5126-2761-4f6f-b2fb-021f462651a2">

My code is:

import time
from transformers import AutoTokenizer
from intel_extension_for_transformers.transformers import AutoModelForCausalLM, WeightOnlyQuantConfig

model_name = "Intel/neural-chat-7b-v1-1"     # Hugging Face model_id or local model
config = WeightOnlyQuantConfig(compute_dtype="int8", weight_dtype="int4")
tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=config)

t=0
while t < 10:
    t += 1
    prompt = "Once upon a time, a little girl"
    inputs = tokenizer(prompt, return_tensors="pt").input_ids
    start_time = time.time()
    gen_tokens = model.generate(inputs, max_new_tokens=300)
    outputs = tokenizer.batch_decode(gen_tokens)
    end_time = time.time()

    # Calculate the time duration between start and end times
    time_duration = end_time - start_time
    print ("total latency, prompt no {}".format(t), time_duration)
    print (outputs)

The log file is attached.
[log.txt](https://github.com/intel/intel-extension-for-transformers/files/12797302/log.txt)

Could anyone please help.

**Comment by a32543254** [comment] 2023-10-07 04:27
Known issue, we are working on it, and will be fixed soon.
Will let you know when the issue is fixed.

**Comment by a32543254** [comment] 2023-10-09 08:47
https://github.com/intel/intel-extension-for-transformers/pull/413
this commit fix this issue, please try again.
I will close this issue if you don't have other comment.

**Closed** 2023-11-16 12:38 UTC
