### ISSUE TITLE
[NeuralChat] Finetuning for LLaVA failing on image + text pairs

### ISSUE THREAD

**Issue by dillonalaird** [intel/intel-extension-for-transformers#1201] opened 2024-01-28 19:01 UTC
This PR https://github.com/intel/intel-extension-for-transformers/pull/1199 fixed training on text only examples, and I tested the fix with text only and image only examples thinking that would resolve the issue overall but there is a new error for text + image examples with an error coming from zero3 in DeepSpeed:

```
Traceback (most recent call last):
  File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py", line 319, in <module>
    train()
  File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py", line 296, in train
    trainer.train()
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 486, in train
    return inner_training_loop(
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 842, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 1367, in training_step
    self.accelerator.backward(loss)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1983, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/DeepSpeed/deepspeed/runtime/engine.py", line 1992, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/DeepSpeed/deepspeed/runtime/zero/stage3.py", line 2097, in backward
    self._get_param_coordinator(training=True).reset_step()
  File "/DeepSpeed/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 203, in reset_step
    raise RuntimeError(f"still have inflight params "
RuntimeError: still have inflight params [{'id': 975, 'status': 'INFLIGHT', 'numel': 16777216, 'ds_numel': 16777216, 'shape': (4096, 4096), 'ds_shape': (4096, 4096), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([2097152])}, {'id': 973, 'status': 'INFLIGHT', 'numel': 4194304, 'ds_numel': 4194304, 'shape': (4096, 1024), 'ds_shape': (4096, 1024), 'requires_grad': True, 'grad_shape': None, 'persist': False, 'active_sub_modules': set(), 'ds_tensor.shape': torch.Size([524288])}]
```

I think the hack the original authors mention in this [PR](https://github.com/haotian-liu/LLaVA/commit/44e0562f9497fb79f042427307472a87d266d90a#diff-4477387d506ccb1897a13972cba26c9da3fad4d3e1c32ec4b8bd8ff7acd3f292) "# FIXME: this is a hacky fix, for deepspeed zero3 to work" was likely to avoid this issue. It might be related to this issue https://github.com/microsoft/DeepSpeed/issues/3156 as I'm guessing it happens when both image and text only examples appear in a batch, so for some examples in the batch it runs through the vision encoder and some examples it doesn't which is sort of like the dynamic forward method referenced in the DeepSpeed issue.

**Comment by dillonalaird** [comment] 2024-01-28 20:08
Looks like you can get different errors coming from the same `reset_step` function in `partitioned_param_coordinator.py`, here's another one:

```
Traceback (most recent call last):                                                                                                                                                                                                                                              
  File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py", line 319, in <module>                                                                                                                         
    train()                                                                                                                                                                                                                                                                     
  File "/intel-extension-for-transformers/intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py", line 296, in train                                                                                                                            
    trainer.train()                                                                                                                                                                                                                                                             
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 486, in train                                                                                                                                                            
    return inner_training_loop(                                                                                                                                                                                                                                                 
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 842, in _inner_training_loop                                                                                                                                             
    tr_loss_step = self.training_step(model, inputs)                                                                                                                                                                                                                            
  File "/intel-extension-for-transformers/optimum-habana/optimum/habana/transformers/trainer.py", line 1367, in training_step                                                                                                                                                   
    self.accelerator.backward(loss)                                                                                                                                                                                                                                             
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 1983, in backward                                                                                                                                                                              
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)                                                                                                                                                                                                                      
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/deepspeed.py", line 167, in backward                                                                                                                                                                           
    self.engine.backward(loss, **kwargs)                                                                                                                                                                                                                                        
  File "/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn                                                                                                                                                                                                             
    ret_val = func(*args, **kwargs)                                                                                                                                                                                                                                             
  File "/DeepSpeed/deepspeed/runtime/engine.py", line 1992, in backward                                                                                                                                                                                                         
    self.optimizer.backward(loss, retain_graph=retain_graph)                                                                                                                                                                                                                    
  File "/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn                                                                                                                                                                                                             
    ret_val = func(*args, **kwargs)                                                                                                                                                                                                                                             
  File "/DeepSpeed/deepspeed/runtime/zero/stage3.py", line 2097, in backward                                                                                                                                                                                                    
    self._get_param_coordinator(training=True).reset_step()                                                                                                                                                                                                                     
  File "/DeepSpeed/deepspeed/runtime/zero/partitioned_param_coordinator.py", line 208, in reset_step                                                                                                                                                                            
    assert_ints_same_as_other_ranks([m.id for m in self.__submodule_order])                                                                                                                                                                                                     
  File "/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn                                                                                                                                                                                                             
    ret_val = func(*args, **kwargs)                                                                                                                                                                                                                                             
  File "/DeepSpeed/deepspeed/runtime/zero/utils.py", line 97, in assert_ints_same_as_other_ranks                                                                                                                                                                                
    raise RuntimeError(f"disagreement between rank0 and rank{dist.get_rank()}: "                                                                                                                                                                                                
RuntimeError: disagreement between rank0 and rank4: rank0: [1018575771, -1145947199, 1011039503, ...
```

I can reproduce this with a smaller json file containing 50 text and 50 image examples [llava_v1_5_mix665k_cleaned_small.json](https://github.com/intel/intel-extension-for-transformers/files/14077556/llava_v1_5_mix665k_cleaned_small.json)

**Comment by lkk12014402** [comment] 2024-01-30 01:12
hi, @dillonalaird

I have reproduced the problem and found that there are some [dynamic shape inputs](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/transformers/modeling/llava_models/llava_arch.py#L108) on the finetuning stage, which have impact on the training. I will rewrite the data preprocess and validate it, then push a pr as soon as possible.

**Comment by lkk12014402** [comment] 2024-01-30 15:19
the issue is fixed by [PR 1212](https://github.com/intel/intel-extension-for-transformers/pull/1212)

**Comment by dillonalaird** [comment] 2024-01-30 20:45
Awesome, thanks @lkk12014402 !

**Closed** 2024-01-31 05:34 UTC

**Comment by BlueBlueFF** [comment] 2024-04-07 02:51
> hi, @dillonalaird
> 
> I have reproduced the problem and found that there are some [dynamic shape inputs](https://github.com/intel/intel-extension-for-transformers/blob/main/intel_extension_for_transformers/transformers/modeling/llava_models/llava_arch.py#L108) on the finetuning stage, which have impact on the training. I will rewrite the data preprocess and validate it, then push a pr as soon as possible.

same question. how to fix it? what is "static shape"(+1 op), thanks
